openapi:
  name: ${spring.application.name}
  title: ${spring.application.name}
  version: '@project.version@'
springdoc:
  swagger-ui:
    operationsSorter: alpha
logging:
  level:
    root: INFO
spring:
  application:
    name: api-private-precheck
  security:
    oauth2:
      client:
        registration:
          citizen:
            authorization-grant-type: client_credentials
            provider: citizen
          party-assets:
            authorization-grant-type: client_credentials
            provider: party-assets
integration:
  citizen:
    connectTimeout: 5
    readTimeout: 30
  party-assets:
    connectTimeout: 5
    readTimeout: 30
