integration:
  citizen:
    url: http://localhost:${wiremock.server.port}/citizen
  party-assets:
    url: http://localhost:${wiremock.server.port}/party-assets
spring:
  security:
    oauth2:
      client:
        provider:
          citizen:
            token-uri: http://localhost:${wiremock.server.port}/token
          party-assets:
            token-uri: http://localhost:${wiremock.server.port}/token
        registration:
          citizen:
            client-id: the-client-id
            client-secret: the-client-secret
          party-assets:
            client-id: the-client-id
            client-secret: the-client-secret
