integration:
  citizen:
    base-url: http://localhost:${wiremock.server.port}/citizen
    oauth2:
      client-id: dummy
      client-secret: dummy
      grant-type: client_credentials
      token-uri: http://localhost:${wiremock.server.port}/token
  party-assets:
    base-url: http://localhost:${wiremock.server.port}/party-assets
    oauth2:
      client-id: dummy
      client-secret: dummy
      grant-type: client_credentials
      token-uri: http://localhost:${wiremock.server.port}/token
spring:
  flyway:
    enabled: false
  jpa:
    hibernate:
      ddl-auto: none
  main:
    banner-mode: 'off'
  sql:
    init:
      mode: always
